### ISSUE TITLE
working with databases in R: April 14 

### ISSUE THREAD

**Issue by jhollist** [rhodyrstats/rhodyrstats.github.io#12]
**What:** Databases in R, Presented by [Jason Becker](http://www.jsonbecker.com/)
**Where:** URI, Kingston, RI,  [Coastal Institute](maps.google.com/?q=1 Greenhouse Rd. Kingston RI 02881), Room 201
**When:** April 14, 1-2:30pm
**Who:** Everyone welcome!
**Hangouts:** TBD

**Comment by matthewabirk** [comment]
I'm not sure if I'll be able to attend. Can you guys record this and make it available online?

**Comment by jhollist** [comment]
We will do the google hangouts again (assuming I remember this time!).  That will stream live and then be available via you tube after.

**Comment by AnneKuhn** [comment]
I will be there- Thanks, Anne Kuhn

**Comment by qkellogg** [comment]
I'll be there! Q
