### ISSUE TITLE
Programming in R: May 12

### ISSUE THREAD

**Issue by jhollist** [rhodyrstats/rhodyrstats.github.io#13]
**What:** Programming in R, 
**Where:** URI, Kingston, RI, room CIK - 201
**When:** May 12, 1-2:30pm
**Who:** Everyone welcome!
**Hangouts:** http://www.youtube.com/watch?v=ljiYHljx4MM

**Comment by qkellogg** [comment]
I'll be there! I have something just before, so it will be tight, but will try not to be late. Thanks Jeff!

**Comment by jhollist** [comment]
I may actually remember to start the hangout this time!  See above for youtube link
