### ISSUE TITLE
co-working session: February 26

### ISSUE THREAD

**Issue by jhollist** [rhodyrstats/rhodyrstats.github.io#14]
**What:** co-working session, details TBD
**Where:** URI, Kingston, RI,  [Coastal Institute](maps.google.com/?q=1 Greenhouse Rd. Kingston RI 02881), Room 201
**When:** February 26, 1-3:00pm
**Who:** Everyone welcome!

Co-working sessions are meant for us to bring our programming challenges and work on them is small to large groups.  If you have an issue you can't solve, bring that.  If you have never opened R before, bring that!  We will make sure to have at least one group going over the basics.

**Comment by marziatamanna** [comment]
I'll join this session. Just let me inform the Room number.

**Comment by jhollist** [comment]
@marziatamanna See above for room.  Any questions, reply here or via email.

**Comment by marziatamanna** [comment]
Thank you so much for reminding me. I will join Friday's session.

Marzia
