### ISSUE TITLE
More ggplot2: February 11

### ISSUE THREAD

**Issue by jhollist** [rhodyrstats/rhodyrstats.github.io#6]
**What:** ggplot2, details TBD
**Where:** URI, Kingston, RI, [Center for Biotechnology and Life Sciences](maps.google.com/?q=120 Flagg Rd. Kingston RI 02881), Room 252
**When:** February 11, 1-2:30pm
**Who:** Everyone welcome!
**Hangouts:** [Event Link](https://plus.google.com/events/cird0ho9h3abuh6gpnnh6sj6mrk)
**Presenter:** Matthew Birk, @matthewabirk
**Sign-up:** http://rhodyrstats.org/sign_up/

This presentation will assume some familiarity with R, but we will review some and we should have enough time after the presentation to help those new to ggplot2 get up to speed.

**Comment by matthewabirk** [comment]
[ggplot2 Cheatsheet.pdf](https://github.com/rhodyrstats/rhodyrstats.github.io/files/124204/ggplot2.Cheatsheet.pdf)

This will be a handy guide for the workshop on Thursday.

**Comment by jhollist** [comment]
In case anyone is waiting for the live stream, We'll be starting up in a few minutes

**Comment by matthewabirk** [comment]
Here is a link to the R code that I used during this presentation.

https://www.dropbox.com/s/9lykpnw15ar4x4f/ggplot2.R?dl=0

**Comment by matthewabirk** [comment]
https://www.dropbox.com/s/9lykpnw15ar4x4f/ggplot2.R?dl=0

**Comment by jhollist** [comment]
Links to the ggplot extensions I mentioned:

[ggplot2 extensions page](https://ggplot2-exts.github.io/)
[ggrepel](https://ggplot2-exts.github.io/ggrepel.html)

**Comment by AnneKuhn** [comment]
Thanks, Matt- great tutorial!
